### PR TITLE
Updated ASCII-Video logic to avoid out of memory issue when processing large videos

### PR DESCRIPTION
**Pull request by codemonkeycxy**
Hey Justin,

I came across your ASCII-Video tool and really loved it! While I was playing with it, I found the script was throwing out of memory exceptions when I asked it to handle a relatively larger video (8MB). I found the the issue was caused by keeping all converted ascii sprites in memory. I made some changes to progressively write results into the output file to make this problem to go away. I'd like to get a review from you :)

The diff might look large because my IDE auto reformatted your original script, I can change that back if you want. The actual diff is pretty small.

I'm very new to Github and it is my first pull request. I'm sure there are things I didn't do correctly. Please feel free to let me know any suggestions and feedback. Thank you very much!

Regards,
Xinyi

### CODE REVIEW

**Comment by fossage** [comment]
Hey Xinyi,

Thanks for taking a look at my project!  I think the changes you made look great.  I'm at work right now so I'll have to wait until I get home to look at them more in depth but I love the idea of progressively writing to the output file and reading the file in as a stream.  Just out of curiosity, why did you make the decision to change the input file type from .js to .yml?

**Comment by codemonkeycxy** [comment]
Hey Justin,

Thanks for reviewing my PR! 

I changed the format from .js to .yml mainly just for the convenice of progressive file writing. If I call `json.toString(convertedPart1)` and `json.toString(convertedPart2)` separately, I would end up having two array-like string in the output file. e.g.

> "[a, b, c]""[d, e, f]"

After switching to yaml format, I have

> -- a
> -- b
> -- c
> -- d
> -- e
> -- f

That made parsing easier in `play` command.

This was just a quick workaround I had at the top of my head, I'm sure there are also other ways of doing this. Feel free to let me know what you think! Thanks!

Xinyi

**Comment by fossage** [comment]
Awesome, well this looks great!  Thanks for the help.

**Comment by codemonkeycxy** [comment]
Wow thanks! I saw your changes to my diff and thanks for fixing the line reader bug! Your code is really neat and I've learnt a lot!

**Pull request merged**
